/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.example.kafka.consumers.UserEventConsumers;
import com.example.kafka.producers.UserEventProducer;
import lombok.extern.slf4j.Slf4j;

import java.util.Locale;

@Slf4j
public class App {

    public static void main(String[] args) throws Exception {
        String mode = args[0];
        switch(mode.toLowerCase(Locale.ROOT)) {
            case "producer":
                log.info("Starting the Producer\n");
                UserEventProducer userProducer = new UserEventProducer();
                userProducer.runAlways();
                break;
            case "consumer":
                log.info("Starting the Consumer\n");
                UserEventConsumers userConsumer = new UserEventConsumers();
                userConsumer.runAlways();
                break;
            default:
                log.error("Mode:{} is not supported", mode);
        }
    }
}
